---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r}

rm(list=ls())

if (!require('plyr')) {
  install.packages("plyr", dependencies = T)
  require("plyr")
  
  install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", "ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))
}

library("ggplot2")
theme_set(theme_bw())
library("sf")

library("rnaturalearth")
library("rnaturalearthdata")

# Library for Map Colorization
library(RColorBrewer)

library(forcats)

if(!require(rgeos)) {
  install.packages("rgeos", dependencies = T)
  require(rgeos)
}

```

```{r}

# load dataset
source('load_data.R')

# Show first 5 entries of dataset
so_20[1:5,]

```
# Initial Assessment
```{r}

sprintf('The 2020 survey had %d respondents and %d variables.', dim(so_20)[1], dim(so_20)[2])

head(so_20_schema)

```


```{r}

# load functions

source('functions.R')

```


```{r}
# Load world data
world <- ne_countries(scale = "medium", returnclass = "sf")

# Create dataframe with all available countries
worldframe <- data.frame(x = world$name)

# Create dataframe with all survey countries
df1 <- so_20 %>% count(Country)

# Rename col for joining
df1 <- df1 %>%
  rename(
    x = Country
  )

# Join both dataframes together
world$surveyPop <- join(worldframe, df1, by='x')

# Change NA to 0
world$surveyPop[is.na(world$surveyPop)] <- 0
```

# Geography

```{r}
# Plot world map
worldpopmap <- ggplot(data=world) +
  # Set plot title
  ggtitle("World map", subtitle = paste0("(", length(unique(world$name)), " countries)")) +
  # Set x and y label
  xlab("Longitude") + ylab("Latitude") +
  # Fill worldmap with summarized survey data
  geom_sf(aes(fill = world$surveyPop$n)) +
  # Scale colors
  scale_fill_viridis_c(option = "plasma", trans = "sqrt") +
  # Customize legend title
  labs(fill = 'Frequency')

# display map
worldpopmap

```

```{r}
# Show previously plotted data in numbers

so_20 %>% 
  count(Country) %>%
    arrange(-n)

```

# Developer Roles

```{r}

df <- data.frame(so_20$DevType)

df

```



# Educational Attainment
```{r}

edu <- so_20 %>% count(EdLevel) %>% arrange(-n)

edu <- na.omit(edu)

edu %>%
  # mutate(freq = fct_reorder(factor(freq), desc(x))) %>%
  ggplot( aes(x=EdLevel, y=n)) + 
    geom_bar(stat='identity') +
    xlab("") +
    coord_flip()

```

# Coding as a hobby

```{r}

# Get hobbyist data
hobby <- so_20 %>% count(Hobbyist)

# Compute percentage
hobby$perc <- perc(hobby$n, length(so_20$Hobbyist))

hobby %>%
  ggplot( aes(x= Hobbyist, y= perc)) + 
    geom_bar(stat='identity') +
    xlab("") +
    coord_flip()
```

# Experience

```{r}

exp <- so_20 %>% count(YearsCode)

# Remove NA
exp <- exp %>% na.omit(exp)

# Select less than 1 year col
#ltone <- exp[grep('Less', exp$YearsCode),]

# Select more than 50 year col
#mtf <- exp[grep('More', exp$YearsCode),]

# Select first 50 cols (without the string cols)
#exp <- exp[1:50,]

# Create new dataframe for storage
newExp <- data.frame()
  

# Convert data to a numerical column
exp$nYearsCode <- as.integer(exp$YearsCode)
exp[grep('Less', exp$YearsCode),]$nYearsCode <- 0
exp[grep('More', exp$YearsCode),]$nYearsCode <- 50

# Select data relted for plotting

newExp['Less than 5 years', 'n'] <- (exp %>% filter(nYearsCode < 5))$n %>% sum() 
newExp['5 to 9 years', 'n'] <- (exp %>% filter(between(nYearsCode, 5, 9)))$n %>% sum()
newExp['10 to 14 years', 'n'] <- (exp %>% filter(between(nYearsCode, 10, 14)))$n %>% sum()
newExp['15 to 19 years', 'n'] <- (exp %>% filter(between(nYearsCode, 15, 19)))$n %>% sum()
newExp['20 to 24 years', 'n'] <- (exp %>% filter(between(nYearsCode, 20, 24)))$n %>% sum()
newExp['25 to 29 years', 'n'] <- (exp %>% filter(between(nYearsCode, 25, 29)))$n %>% sum()
newExp['30 to 34 years', 'n'] <- (exp %>% filter(between(nYearsCode, 30, 34)))$n %>% sum()
newExp['35 to 39 years', 'n'] <- (exp %>% filter(between(nYearsCode, 35, 39)))$n %>% sum()
newExp['40 to 44 years', 'n'] <- (exp %>% filter(between(nYearsCode, 40, 45)))$n %>% sum()
newExp['45 to 49 years', 'n'] <- (exp %>% filter(between(nYearsCode, 45, 49)))$n %>% sum()
newExp['50 years or more', 'n'] <- (exp %>% filter(nYearsCode >= 50))$n %>% sum() 

#
#between_c(exp, exp$YearsCode, 5, 9)$n

# Compute percentages
newExp$perc <- perc(newExp$n, sum(exp$n))

# Move idx names to a col
newExp$desc <- rownames(newExp)

# TODO fix order of plotting
# newExp$desc <- factor(newExp$desc, levels= newExp$desc[order(newExp$perc)])

newExp %>%
  ggplot( aes(x= rownames(newExp), y= perc)) + 
    geom_bar(stat='identity') +
    xlab("") +
    coord_flip()

```







